### ISSUE TITLE
doesn't compile on reactos

### ISSUE THREAD

**Issue by Veerteex0** [maxkofler/Z80Emu#16]
Hello,
this shit doesn't compile on reactos.
PLS HELP
GREETS

**Comment by Veerteex0** [comment]
@maxkofler pls help

**Comment by Veerteex0** [comment]
@maxkofler i need this very much

**Comment by Veerteex0** [comment]
@maxkofler why are you troll pls help me now

**Comment by maxkofler** [comment]
We don't support react

**Comment by zimsneexh** [comment]
+1 for supporting reactOS
