### ISSUE TITLE
DLL missing in the 0.0.1 release

### ISSUE THREAD

**Issue by Benji377** [maxkofler/Z80Emu#19]
Unable to execute ".exe" file on Windows 10, it says I am missing a dll file and that the reinstallation of the program might fix it, but it doesn't. Take a look at the following error message:

![image](https://user-images.githubusercontent.com/50681275/119464923-82367e80-bd43-11eb-8487-e5f159bc6754.png)

**Comment by maxkofler** [comment]
Solved -> linked all libraries static to prevent this error. Additional investigation is going in this way to dynamically link to  libgcc and libstdc++ to cut on executable size
